hash-format = "sha256"

[[files]]
file = "mods/balm.pw.toml"
hash = "639d1e087044f56c3d414841a577d00030e6f5c057540d9a33f4c1cde98e0437"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "a9337bd8ac7a93a3e5f622ac5e288baa049ed685d908e6771bd00dddebf0d278"
metafile = true

[[files]]
file = "mods/diagonal-fences.pw.toml"
hash = "e96c8419bbcfb7950cd2f14187b632d3f162a7e873a48015f49b43716af119b9"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "79625467f94812a83eb6fbf4e1d3884418937cc5b07fc708d05b7ab11dac16a5"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "098d6976a738658ca490cc58e9fab19f06cd1a7b23199b6f1ee108d866333e22"
metafile = true

[[files]]
file = "mods/followers-teleport-too.pw.toml"
hash = "15d14b715d89435099cdaf28f74f7458ffd82e34e37c1e6cd0a9cdb2baa3debe"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "9a8c273d0efcf679d04d77ab37521c05978caff642a6c2b867d2fa2cdc8b168e"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "5f40e2db6037f733566c81e8f11ca3c425d738eb5a182658691f36d041b5df40"
metafile = true

[[files]]
file = "mods/inventory-management.pw.toml"
hash = "b50651c2c054ff67985150b5a80198fda6606545f7d68e92548d1a7fea4c0914"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "4ed061d122cb39f34ed730984c7bcf03437250f24a21975203bb4598d7d86a14"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "8943d352c205e18399c893fb7135dc756f53ecc08fb3fb4b4bac048a788f47d0"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "22d23e00644963c4f299d87453c287f6b22749b4bec44dcd58d7d0e0144d4fd6"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "03aeb028187b13a940b7140789a7701febaacfb8fbad9fcbd6344c197df31f7e"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "fb7ac2b9ede78fcb812388882addc3e6de5e4176e570acc5332bae6088ec2d04"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "0535b2aae533bf85d7382866c456ed491db5da4784f249a370f796280014340d"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "5dd45d5fd5e1ae2bd521b93a70b83c69b57ada18f424c6562d8c6ea9980cfb3e"
metafile = true

[[files]]
file = "mods/no-hostiles-around-campfire.pw.toml"
hash = "c6adb9f33e7a8c8d698839b7c480c1f8ec1e1597a995cfa58e7a33aa293828ef"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "4762935a3ab92c3ad07f3eb43a7bb8f9997066c9f8e9c68745f286e395f7b51e"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "17ee671cddcc590d308b34dff6eaf75a4cd066556dc611f3322e974d98bd3e9f"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "e8c961dbadf2dde334c857d0b42a6c6452aa77a146cf80d4febf7f46e4ac2ef6"
metafile = true

[[files]]
file = "mods/trashslot.pw.toml"
hash = "343644dce1420ab6a3e0d2780c65e8c4abfe0a76ba63229e72495333a77ebb45"
metafile = true

[[files]]
file = "mods/tree-harvester.pw.toml"
hash = "7b976155d02000a064de326c3918686bc8be05125a16570659c5f5c9feab768b"
metafile = true

[[files]]
file = "mods/tweakeroo.pw.toml"
hash = "fb1838277d110e0b7cc82a9b03db6f9b08198ad8396bf789fa339454ba7c1682"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
hash = "a4e360ff3653483b148b0dc6087e4840b01792e94565d28607c15e06f1815ddb"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "cfa4ddfc8999e7be331c6dad1f2a0372f996243241d21697939e6838b3402c6d"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "22052f42b1b73226d9508ef42af962471c79c7daa281aac66a82a90c7d7bb9e5"
metafile = true

[[files]]
file = "packwiz-installer-bootstrap.jar"
hash = "a8fbb24dc604278e97f4688e82d3d91a318b98efc08d5dbfcbcbcab6443d116c"

[[files]]
file = "packwiz-installer.jar"
hash = "c9f646908d340d84773948a9a7d98bc1dae250d35e1016dc6e2b8459760b5598"

[[files]]
file = "resourcepacks/borderless-glass.pw.toml"
hash = "b913bffde7a6bbdad173ae643cc1f3103a3f4c114d10d0a2dfb44536135ca480"
metafile = true

[[files]]
file = "resourcepacks/invisible-armor-model.pw.toml"
hash = "613a1a5f7adf3168a6fbfbdd3beeaeb0b4dc1c4bf93c1ac717611c6a0f34e0d5"
metafile = true
