name = "Cosmerecraft"
author = "theCr0w"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c807c143aafc81272e1ea9753c9ced0a1383c6827af88924323b5733c48926f2"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
