name = "Cosmerecraft"
author = "theCr0w"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "426f3bc05cafd4ab0795e4c49b9dc2b6f8c7b44f4fcbd5f5634c139473859f22"

[versions]
fabric = "0.17.2"
minecraft = "1.21.10"
