name = "Cosmerecraft"
author = "theCr0w"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d13facccf7035872ba68e6e0486ad0d0925fbb5701d7701f7af12afa64235b9"

[versions]
fabric = "0.17.2"
minecraft = "1.21.10"
