name = "Cosmerecraft"
author = "theCr0w"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eaf68451832ce1ec0cfe11ff5fd6d1e2dd4c3b65dba2e0042d6ba6884942f2ec"

[versions]
fabric = "0.17.2"
minecraft = "1.21.10"
