name = "Cosmerecraft"
author = "theCr0w"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fa45b6bb4ecba220b1a164bcfbaf26e5d2de9e703c5aee68331d86b51e96e7e"

[versions]
fabric = "0.17.2"
minecraft = "1.21.10"
