name = "Cosmerecraft"
author = "theCr0w"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f75e722c3f273e5d39d20b4079384f41dc1c7ce1b7fd7705d984fffe52e4aec"

[versions]
fabric = "0.17.2"
minecraft = "1.21.10"
