name = "Cosmerecraft"
author = "theCr0w"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b487b5252b1a302fd4323bca3aab6021df59f2b55acd2a5f957df472730756e"

[versions]
fabric = "0.17.2"
minecraft = "1.21.10"
