name = "Cosmerecraft"
author = "theCr0w"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9416d9f2c109df0ac3d8e82df83d86b91a205392ea366958f508a1c649c5704b"

[versions]
fabric = "0.17.2"
minecraft = "1.21.10"
