name = "Cosmerecraft"
author = "theCr0w"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1935743000df206f885326e4633c754e869ddd919e568b9bf8430a41b02c31f7"

[versions]
fabric = "0.17.2"
minecraft = "1.21.10"
